### ISSUE TITLE
Sprites => WebGL Shaders render a solid background for transparent PNGs

### ISSUE THREAD

**Issue by catalinberta** [WebGLSamples/WebGLSamples.github.io#1]
I've recently come across your awesome sprite solution in WebGL, thanks for the awesome work!

Back story: I have restructured and simplified your WebGL solution to work strictly with simple spritesheet animations so I can add it to a small spritesheet animation library, which mainly plays spritesheet animations in WebGL and falls back to canvas if WebGL is not supported.

Problem: In WebGL, the fragment shader (I believe) is unable to render the alpha channel properly from PNG files, as it renders a solid background.

[JsFiddle here](http://jsfiddle.net/dfjcdg1p/1/)

You have two animations there with the same spritesheet, first one is in WebGL, second on is run in Canvas, to tell the difference.

Any clues as to what triggers this and a work around it?

**Comment by greggman** [comment]
I'm not sure what you're trying to do.

To render alpha correctly in WebGL you need to 

1. Turn on blending

        gl.enable(gl.BLEND);

2. Set the blend function

        // this is for pre-mutliplied alpha just like Canvas
        gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA);

3. Load your images with premultiplied alpha OR premultiply them in the shader

        // the load with pre-mutiplied alpha 
        gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, true);

    or

        // premultiply in the shader
        gl_FragColor = vec4(gl_FragColor.xyz * gl_FragColor.a, gl_FragColor.a);

4. Draw back to front

    Just like the canvas 2d api you need to draw stuff in the back before stuff in the front

**Comment by catalinberta** [comment]
Worked like a charm, thank you!
