### ISSUE TITLE
More max fish

### ISSUE THREAD

**Issue by null77** [WebGLSamples/WebGLSamples.github.io#12]
Thanks for the Aquarium demo! We use it for comparative benchmarking of WebGL implementations. However, we've run into a problem where in some cases 4k fish is not enough. It would be useful to have an 8k fish view, and maybe even 16k.

**Comment by greggman** [comment]
More fish were added

https://github.com/WebGLSamples/WebGLSamples.github.io/pull/13/commits/f3580bd3b047918b2feacec74c67426ebd64b129

Also you can just pass the number of fish in the URL

https://webglsamples.org/aquarium/aquarium.html?numFish=12345

**Comment by null77** [comment]
So many fish! Thank you.
