### ISSUE TITLE
Could the Aquarium Be Run Dynamically and use Three.js?

### ISSUE THREAD

**Issue by computersarecool** [WebGLSamples/WebGLSamples.github.io#3]
Thanks for all the work you have contributed to WebGL.  

I have been drawn to this Aquarium example for a long time and I have two questions:

A. Could you use a library such as Three.js  to make this?

B.  My real question is about the general technique:

Is the example playing synched video or is there an actual 3D scene rendered somewhere (like on a server), that each monitor / computer has a "view" into?

I am wondering if it is possible, using Three.js and Websockets, to make a flat canvas looking into a single 3D scene using different computers.  That way I could roll a ball in the 3D scene on one computer, and have it roll onto the screen of another.

This last sentence is what I am all about and would love to know if you think I could accomplish this.  Thanks

**Comment by greggman** [comment]
There's an explanation of how it works here

http://webglsamples.org/aquarium/README.html

It's 8 machines. The only thing synced are view settings and time using websockets

[Here's another example program](https://github.com/greggman/hft-syncthreejs) using [happyfuntimes](http://docs.happyfuntimes.net) and three.js

**Comment by computersarecool** [comment]
This just pointed me to (even more) "epic" stuff you've made......So friggin cool.Thanks for providing me stuff to work on!
