### ISSUE TITLE
WebGLSamples code licence

### ISSUE THREAD

**Issue by gvalcaza** [WebGLSamples/WebGLSamples.github.io#36]
Good afternoon,

I'm currently working on integrating a web browser onto i.MX-based embedded systems via a custom Yocto layer. As part of the layer, I was thinking of integrating a recipe for the WebGL samples in this repo.

The idea is that, when building a Yocto project with this layer, said recipe would download this repo and install a subset of the examples into the Yocto Linux image, so that they are accessible on the device as soon as the image boots. The main reason I want to install the samples in the device instead of accessing them via the already available webpage (https://webglsamples.org/) is to be able to test the browser's WebGL capabitilies without having to be connected to the internet, in cases where internet access isn't possible or just to serve as examples for local web applications that make use of WebGL.

Having said this, I haven't found any information on the licence of this project, so I don't know if the scenario I mentioned is possible. Does this project have any limitations regarding distribution/modification of its code? If so, would a Yocto recipe that downloads this repo and install a subset of samples onto a Yocto image fit within said limitations?

Otherwise, I can link directly to https://webglsamples.org/.

Best regards and thanks in advance,
Gabriel

**Comment by greggman** [comment]
many of the files have the license at the top of the file but I added a LICENSE.md

**Comment by gvalcaza** [comment]
Perfect! I noticed a licence in some of the files I looked at, but I wanted to be completely sure before moving forward with the development of the layer :)
Thank you very much!
